enum OpKind {
  INVALID_OP = 'INVALID_OP',
  INC_PTR = 'INC_PTR',
  DEC_PTR =  'DEC_PTR',
  INC_DATA = 'INC_DATA',
  DEC_DATA = 'DEC_DATA',
  READ_STDIN = 'READ_STDIN',
  WRITE_STDOUT = 'WRITE_STDOUT',
  LOOP_SET_TO_ZERO = 'LOOP_SET_TO_ZERO',
  LOOP_MOVE_PTR = 'LOOP_MOVE_PTR',
  LOOP_MOVE_DATA = 'LOOP_MOVE_DATA',
  JUMP_IF_DATA_ZERO = 'JUMP_IF_DATA_ZERO',
  JUMP_IF_DATA_NOT_ZERO = 'JUMP_IF_DATA_NOT_ZERO',
};

export { OpKind };
