enum OpKind {
  INVALID_OP = 'INVALID_OP',
  INC_PTR = 'INC_PTR',
  DEC_PTR =  'DEC_PTR',
  INC_DATA = 'INC_DATA',
  DEC_DATA = 'DEC_DATA',
  READ_STDIN = 'READ_STDIN',
  WRITE_STDOUT = 'WRITE_STDOUT',
  LOOP_START = 'LOOP_START',
  LOOP_START_END = 'LOOP_START_END',

  // Custom
  INC_OFFSET = 'INC_OFFSET',
  DEC_OFFSET =  'DEC_OFFSET',
  LOOP_SET_TO_ZERO = 'LOOP_SET_TO_ZERO',
  LOOP_MOVE_PTR = 'LOOP_MOVE_PTR',
  UNROLL_LOOP_MOVE_PTR_UNTIL_ZERO = 'UNROLL_LOOP_MOVE_PTR_UNTIL_ZERO',
  LOOP_MOVE_DATA = 'LOOP_MOVE_DATA',
  LOOP_MOVE_DATA_END = 'LOOP_MOVE_DATA_END',
  JUMP_IF_DATA_ZERO = 'JUMP_IF_DATA_ZERO',
  JUMP_IF_DATA_NOT_ZERO = 'JUMP_IF_DATA_NOT_ZERO',
  SET_DATA = 'SET_DATA',
  STORE_DATAPTR = 'STORE_DATAPTR',
  GET_DATAPTR = 'GET_DATAPTR',
  MUL_INC_DATA = 'MUL_INC_DATA',
  MUL_DEC_DATA = 'MUL_DEC_DATA',
  SEARCH_LOOP = 'SEARCH_LOOP',
  RUN_FUNC = 'RUN_FUNC',

  // Legacy
  RESET_DATA_RANGE = 'RESET_DATA_RANGE',
  DATA_LOOP = 'DATA_LOOP',
  DATA_LOOP_ADD = 'DATA_LOOP_ADD',
  DATA_LOOP_SUB = 'DATA_LOOP_SUB',
  DATA_LOOP_END = 'DATA_LOOP_END',
};


export { OpKind };
